### ISSUE TITLE
missing requirement

### ISSUE THREAD

**Issue by topac** [cardinalblue/rest-graph#11]
Rakefile requires a missing file

``` ruby
require "#{dir = File.dirname(__FILE__)}/task/gemgem"
```

**Comment by godfat** [comment]
This is in a git submodule. Try to run this:

```
git submodule init
git submodule update
```

In the mean time, I'll put a automation for this in Rakefile.
Thanks for letting me know.

**Comment by godfat** [comment]
Please let me know if this works for you, thanks!

**Comment by topac** [comment]
works great thanks :)
