### ISSUE TITLE
README.rdoc authorize_url example wrong

### ISSUE THREAD

**Issue by betelgeuse** [cardinalblue/rest-graph#2]
# OAuth utilites:
 # https://graph.facebook.com/oauth/authorize?client_id=123&
 RestGraph.new.authorize_url(:redirect_uri => 'http://w3.org/')

This doesn't result in the url in the comment because '123' is not passed as :app_id to .new

**Comment by godfat** [comment]
README.rdoc: be more careful to example, thanks betelgeuse, closed by cace471c844644e8c5fb4630fe6b3a52f08bc869
