### ISSUE TITLE
Regular expression causes malformed URL in RailsUtil

### ISSUE THREAD

**Issue by jcoyne** [cardinalblue/rest-graph#4]
In the method "rest_graph_normalized_request_uri"

Consider a uri that has the form:  "/?code=123&foo=bar"

When the regular expressions are run

<pre><code>
>> path.sub(/[\&\?]session=[^\&]+/, '').
?>         sub(/[\&\?]code=[^\&]+/, '')
=> "/&foo=bar"
</code></pre>

Which is not the URL we want.

<pre><code>
path.sub(/(\&|\?)session=[^\&]+\&?/, '\1').sub(/(\&|\?)code=[^\&]+\&?/, '\1')
</code></pre>

is a better solution which retains the leading ? if it's there.

Another issue in this method is request.request_uri is deprecated in rails 3.  request.fullpath works in Rails 3, but is not present in Rails 2.x

**Comment by godfat** [comment]
use URI.parse to handle query string better, add tests for it, closed by 454dc9602df7d6a17270153fa975bd401785e7af
